{
 "title": "VT vs WebFlux",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"virtual-threads\"}[30s]))",
     "legendFormat": "Virtual Threads"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"webflux\"}[30s]))",
     "legendFormat": "WebFlux"
    }
   ]
  },
  {
   "title": "Response Time (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"virtual-threads\"}[1m])) by (le))",
     "legendFormat": "Virtual Threads P95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"webflux\"}[1m])) by (le))",
     "legendFormat": "WebFlux P95"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=\"/docker/b9c7cbf5472b1dcdc09f9ec839401e70fd6b58e85980277df03de76d108f014e\"} / 1024 / 1024",
     "legendFormat": "Virtual Threads (MB)"
    },
    {
     "expr": "container_memory_usage_bytes{id=\"/docker/76a7f50ea30edceecf1d9e237ee4046e20bcf117b60866b5762111bd08b991da\"} / 1024 / 1024",
     "legendFormat": "WebFlux (MB)"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/docker/b9c7cbf5472b1dcdc09f9ec839401e70fd6b58e85980277df03de76d108f014e\"}[1m]) * 100) / 2",
     "legendFormat": "Virtual Threads CPU %"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/docker/76a7f50ea30edceecf1d9e237ee4046e20bcf117b60866b5762111bd08b991da\"}[1m]) * 100) / 2",
     "legendFormat": "WebFlux CPU %"
    }
   ]
  }
 ]
}